### ISSUE TITLE
Move abstract tracer to contrib

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#104]
This comes over and over again (most recently [here](https://github.com/opentracing/opentracing-java/pull/68#issuecomment-281818073)), I think we should address this. The reasons for moving abstract tracer out of `opentracing-java` are:
  1. it is not used by many (most?) existing production tracers
  1. it does not necessarily reflect how the tracers should be implemented
  1. it has some unexpected, but hard to remove design choices  (#55)
  1. it often confuses newcomers being in the official OT Java repo
  1. it's not clear if there are active maintainers of `opentracing-java` who also want to maintain the abstract tracer (and they can still do it in contrib)
  1. abstract tracer is not needed for development of OT API itself, because implementation questions can be tried out in Noop and Mock tracers, both of which do not extend the abstract tracer.

**Comment by bhs** [comment]
I will cc @michaelsembwever since he is most likely to come to its defense. :)  That said, I haven't heard from mck in many moons so I'm not confident that he has cycles to weigh in.

I am wildly in favor of this move and merely lack the time to actually do the mechanical work involved. If we're unable to find the time to move it, at least we could change the SpanContext/SpanBuilder relationship which is surprising to all comers.

**Comment by wu-sheng** [comment]
@yurishkuro +1, I have explained so many times to my co-workers... Many of them thought they are part of Spec or Spec-java, and must be followed when implement OT-SPEC-JAVA.

I am glad about this.

**Comment by sjoerdtalsma** [comment]
@yurishkuro 👍 
My biggest gripe with this is it forces subclasses to become residents of the `io.opentracing.impl` package which could become real crowded real soon if this continues to be encouraged.

**Comment by bhs** [comment]
Closed via #121.
