### ISSUE TITLE
Add tracing level

### ISSUE THREAD

**Issue by hloos** [opentracing/opentracing-java#204]
Hi guys,

Unless I am mistaken, there is no tracing level in the current implementation.

However, as a user, it could be interesting to have different level for tracing. Example: BASIC / FINE / FINER / FINEST or something similar... which would come from user configuration.

Moreover, we should have a way to check the current supported level before triggering distributed tracing (span preparation, ...) - for performance purpose. I meanly think in async environments where ActiveSpan is hardly usable and where we need to build spans, start and stop them manually.

Also, sampling could be done differently according to the level (specified by user configuration as well) and could be done the earliest, when the user would check for tracing availability ->something like isTracingAvailable(Level level) - for perfomance purpose as well.

Let me know what are your thoughts about that, I can contribute if necessary.

Cheers !

**Comment by yurishkuro** [comment]
if you search old issues you may find discussions about log levels and arguments against them. We should probably have an FAQ entry with a stated position.

**Comment by tedsuo** [comment]
Hi @hloos, I don't think you need tracing levels for Spans. I would suggest that you use spans in a course-grained manner, and for fine-grained information use the Span Log API. If you're having performance issues, you are probably are creating more spans than you need. Logs are usually much cheaper.

Like Yuri said, there's no "log level" currently, as there is no agreement on how many levels there should be, o if it is appropriate for OT to define one. 

In the meantime, I would suggest making a helper library that can be configured at application init as to what log level will be emitted:

```go
Debug(span, ...logs)
Info(span, ...logs)
Warn(span, ...logs)
Error(span, ...logs)
```

**Comment by daschl** [comment]
@hloos I also agree with the assertion that "tracer levels" are fundamentally not needed in terms of `opentracing-api` as a core concept.

What I found in practice (and happy of course to take the discussion forward) is that the need for a "trace level" stems from the fact that either too little or too much information is being fed into the tracer depending on the situation. But what is "too much" or "too little" depends both on the application context and a temporal aspect. I have found the following to be more helpful:

 - On the Tracer side, good tracers provide sampling mechanisms to deal with overload and may be able to adjust at runtime based on the current issues of the system rather than a predefined level.
 - On the span-producing side, don't think of it as levels but rather allow to enable/disable the creation of certain "nesting level" spans depending on the depth needed. For example provide configuration options that don't create "I/O" sub-spans of a request/response or if needed in development add even more fine-grained span and span tags. Is this informational? or debug? or a warning? I don't think this concept of levels allows to properly represent the concept of a span/trace.

Finally, if you need to log spans in the traditional sense, I recommend that you just implement a simple tracer which accepts spans and then log hem based on what you need (and this is where you can map certain spans to log levels as you see fit in your domain logic) and then discard or forward to another tracer.

**Comment by hloos** [comment]
@daschl I don't work anymore on the project that has required this "tracer level notion". However, I have got a couple of questions about your answer.

When you talk about "tracer side", I guess your refer (for instance) to the different available UIs as jaeger UI or zipkin, right ? I did not know about the sampling capability of such a tool. Indeed, at least in dev mode where performance is not critical, it would have been very useful for us.

@daschl @tedsuo 
On the span-producing side, ie the application, I completely agree with you since, basically, the "tracing level" we needed was a way to prevent from creating costly and useless span when it was not needed. Finally, we ended up doing our own  levels. As you certainly noticed, in the original message, I used "basic/fine/finer/finest" level names and not the ones usually used by the loggers (debug/warn/error) which does not stand for the level notion we wanted to intoduce.

**Comment by daschl** [comment]
@hloos by the "tracer" side I just mean implementations of the `Tracer` interface in general. Stuff like Jaeger has a UI and also implements the sampling for example. In a custom one I've been developing for example I'm aggregating "on the fly" and only storing the top 10 slowest spans in a given time interval which are then emitted to an external recipient (can be a log as well).

With that, is this question resolved?

**Comment by hloos** [comment]
@daschl Yes this question is resolved. Thanks !
