### ISSUE TITLE
Should NoopSpanBuilder still extend NoopSpanContext?

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-java#255]
Hi! I'm working on the C# version of opentracing-noop and I've seen that `NoopSpanBuilder` [extends NoopSpanContext](https://github.com/opentracing/opentracing-java/blob/master/opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java#L24). 

Is there still any use for this or is this no longer necessary due to #55, #121 ?

**Comment by carlosalberto** [comment]
Hey @cwe1ss 

It looks to me like #121 included a lot of changes after refactoring (19 files in total), and my bet is that `NoopSpanBuilder` was forgotten all along (I think this because in the PR/Issue there's no mention of `NoopSpanBuilder`).

I tried updating the code to remove that `implements SpanContext` + minor tuning, and everything works just fine, so I could finish the patch up and send it as a final fix piece.

Does it make sense to you guys? @yurishkuro @bhs (author of #121) You may remember it better ;)

**Comment by bhs** [comment]
@carlosalberto @cwe1ss sorry for the delay! I don't know why that inheritance relationship would still be necessary. If everything compiles without it, we should def remove. Thanks for asking.
