### ISSUE TITLE
Add javadoc to public methods/interfaces in the core OpenTracing API

### ISSUE THREAD

**Issue by bhs** [opentracing/opentracing-java#36]

**Comment by michaelsembwever** [comment]
I'm no fan of such enforcement.

I've seen first hand across multiple teams with various experience that going from enforced apidocs on every class and method to aiming for a little  apidoc as possible actually produces better code.  
Try to write code that's so obvious that comments are superfluous.
Do this with meaningful class, method, and field names.
Do this but having small methods. Even pull out a few statements into a separate method so that with the new method name you have a placeholder for descriptive text, instead of adding a comment.

Such a practice does rely on peer review to include pointing out anything that is unclear and needs to be better described (or referenced back to specifications).
This creates comments where others, not the author, deem necessary.

So the author tries to write code that is simple and intuitive enough, through the use of the code's structure and nomenclature, that comments are reduced to a bare minimum. At the same time the author always accepts the request to add comments where reviewers find them warranted.

This is not something that I previously believed in but seeing the significantly increase in code quality, from average to experienced developers, and the constructive discussions it introduces into the peer review process, was so astounding that I changed my mind and have never looked back.

**Comment by bensigelman** [comment]
@michaelsembwever I see and agree with your point for code in large systems (e.g., Cassandra), but for a very thin facade API like OpenTracing I'd say it's worth maintaining excellent javadoc for the top (`-api`) layer, which is what I'm referring to here. Honestly, this is like an hour of work max, probably rarely to be revisited or repeated given the eventual stability of this API. Sound better this way?

**Comment by michaelsembwever** [comment]
A more accurate title would help then :-)

Everything that implements the specification, for example, warrants documentation.

**Comment by bensigelman** [comment]
@michaelsembwever 

> A more accurate title would help then :-)

Mea culpa! I tried to fix this just now...

**Comment by tedsuo** [comment]
Spring cleaning here: the current API is well documented, so I'm closing this. Feel free to reopen or create a new issue if there is further debate of the level/type of documentation.
