### ISSUE TITLE
Create dummy user for travis deploys

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing-java#41]
My user being in the commit log during releases is confusing, as it is easy to assume I'm doing the releases! The travis yaml could be re-encrypted with a dummy account.

**Comment by yurishkuro** [comment]
In Python ecosystem the releases are often done by `zest.releaser`, which is a script that does similar version/changelog manipulations and pushes a release tag to VCS, and the CI is configured to publish artifacts when it sees the tag. Since all changes are made locally, there's no question of which user makes them.

**Comment by tedsuo** [comment]
Spring cleaning here: closing this as I believe it has been resolved. Please reopen or create a new issue if there's more to be done regarding travis/commits/releases/etc.
