### ISSUE TITLE
Make abstract classes public

### ISSUE THREAD

**Issue by objectiser** [opentracing/opentracing-java#52]
Just wondering if there is a particular reason why the abstract classes are not public? If not, I'll submit a PR.

**Comment by michaelsembwever** [comment]
The reason they are currently abstract is because they benefit from not being as public as the API so to differientate their purpose as opentracing implementers api from opentracing user api.

Implementers can have immediate and abstract subclasses can sit in the io.opentracing package, and their final classes subclassing these in whatever package they would like.

It is advantageous to have opentracing's APIs as closed as possible to begin with to avoid unintentional api breakages along the way. Implementers instead opening the visibility of the abstract classes is less of a concern since the implementers own classes are not exposed to as great an audience.

This is good practice in api design.
Nothing is permanent though. The api design practice is that apis are opened when clear examples to open them are provided, ie consumer-driven design.

**Comment by objectiser** [comment]
Ok thanks for the explanation.

**Comment by michaelsembwever** [comment]
Np. Feel free to open when there's the use-case to illustrate the benefit.
